// --- START OF COMPLETE src/app/page.tsx ---
'use client';

import { useState } from 'react';
import ChatInterface from '@/components/chat/ChatInterface';
import BulletEditor from '@/components/bullets/BulletEditor';
import OERPreview from '@/components/oer/OERPreview';
import RankSelector from '@/components/ui/RankSelector';
import SpeechHint from '@/components/speech/SpeechHint'; // Assuming you have this component
import { Card } from '@/components/ui/card'; // Assuming Card is from shadcn

// Define the structure for a bullet
// This should match the BulletData interface sent by ChatInterface
interface Bullet {
  id: string;
  competency: string;
  content: string;
  isApplied: boolean;
  category: string;
  createdAt: number; // Added to match BulletData
  source?: string;   // Added to match BulletData
}

export default function Home() {
  const [activeTab, setActiveTab] = useState<'chat' | 'bullets' | 'oer'>('chat');
  const [bullets, setBullets] = useState<Bullet[]>([]);
  const [rankCategory, setRankCategory] = useState<'Officer' | 'Enlisted'>('Officer');
  const [rank, setRank] = useState('O3'); // Default Officer rank

  // Default ranks for when category changes
  const defaultOfficerRank = "O1"; // Example, adjust as needed
  const defaultEnlistedRank = "E4"; // Example, adjust as needed

  // Handler for Rank Category dropdown change
  const handleRankCategoryChange = (newCategory: 'Officer' | 'Enlisted') => {
    setRankCategory(newCategory);
    // Reset the specific rank to a default for the new category
    setRank(newCategory === 'Officer' ? defaultOfficerRank : defaultEnlistedRank);
  };

  // Handler for Specific Rank dropdown change
  const handleRankChange = (newRank: string) => {
    setRank(newRank);
  };

  // Handler for when a new bullet is generated by ChatInterface
  // Enhance the handler in page.tsx

const handleBulletGenerated = (newBullet: Bullet) => {
  console.log("page.tsx: handleBulletGenerated received new bullet:", newBullet);
  
  // Verify the bullet has all required fields
  if (!newBullet.id || !newBullet.competency || !newBullet.content) {
    console.error("page.tsx: Invalid bullet data received:", newBullet);
    return;
  }
  
  // Update the state with the new bullet
  setBullets(prevBullets => {
    const updatedBullets = [...prevBullets, newBullet];
    console.log("page.tsx: Updated bullets state:", updatedBullets);
    return updatedBullets;
  });
  
  // Switch to the Bullets tab
  setActiveTab('bullets');
  console.log("page.tsx: Switched to 'bullets' tab");
};

  // Handler for when bullets are modified in BulletEditor
  const handleBulletsChanged = (updatedBullets: Bullet[]) => {
    setBullets(updatedBullets);
  };

  // Helper to get the main evaluation title
  const getEvaluationTitle = () => {
    return rankCategory === 'Officer' ? 'Officer Evaluation Report' : 'Enlisted Evaluation Report';
  };

  // Helper to get the label for the preview tab
  const getPreviewTabLabel = () => {
    return rankCategory === 'Officer' ? 'OER Preview' : 'Evaluation Preview';
  };

  return (
    <main className="min-h-screen p-4 md:p-8 bg-background text-foreground"> {/* Ensure base theme colors */}
      <div className="mx-auto max-w-6xl">
        <h1 className="mb-6 text-center text-2xl font-bold md:text-3xl text-foreground">
          USCG {getEvaluationTitle()} Generator
        </h1>

        {/* Rank selector card */}
        <Card className="mb-6 p-4 md:p-6 bg-card text-card-foreground border border-ring shadow-sm">
          <RankSelector
            selectedRankCategory={rankCategory}
            selectedRank={rank}
            onRankCategoryChange={handleRankCategoryChange}
            onRankChange={handleRankChange}
            // Pass styling props if RankSelector accepts them for dark mode consistency
            // selectClassName="bg-input text-foreground dark:bg-muted dark:text-foreground"
            // labelClassName="text-card-foreground"
          />
        </Card>

        {/* Tab navigation */}
        <div className="mb-6">
          <div className="flex border-b border-border"> {/* Use theme border */}
            {(['chat', 'bullets', 'oer'] as const).map(tab => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-2 font-medium transition-colors ${
                  activeTab === tab
                    ? 'border-b-1 border-border text-ring' // Use theme primary
                    : 'text-muted-foreground hover:text-foreground' // Use theme muted/foreground
                }`}
              >
                {tab === 'chat'
                  ? 'Generate Bullets'
                  : tab === 'bullets'
                  ? 'Manage Bullets'
                  : getPreviewTabLabel()}
              </button>
            ))}
          </div>
        </div>

        {/* Main content card - uses bg-card */}
        <Card className="p-4 md:p-6 bg-card text-card-foreground border border-ring shadow-sm">
          {activeTab === 'chat' && (
            <ChatInterface
              onBulletGenerated={handleBulletGenerated} // Pass the correct handler
              rankCategory={rankCategory}
              rank={rank}
              // You can pass initialMessages to ChatInterface if needed
            />
          )}
          {activeTab === 'bullets' && (
            <BulletEditor
              initialBullets={bullets}
              onBulletsChanged={handleBulletsChanged}
            />
          )}
          {activeTab === 'oer' && (
            <OERPreview
              bullets={bullets}
              rankCategory={rankCategory}
              rank={rank}
            />
          )}
        </Card>

        <p className="mt-8 text-center text-sm text-muted-foreground">
          This application helps generate performance bullets and create {getEvaluationTitle()}s.
        </p>
      </div>

      {/* Speech-to-text hint component (if you have it) */}
      {/* <SpeechHint /> */}
    </main>
  );
}
// --- END OF COMPLETE src/app/page.tsx ---